CREATE DATABASE TABLASRELACIONADAS
GO
USE TABLASRELACIONADAS
GO

CREATE TABLE CATEGORIA(
IDCATE INT IDENTITY (1,1) PRIMARY KEY,
CATEGORIA NVARCHAR (100) NOT NULL
)
GO

CREATE TABLE MARCA(
IDMAR INT IDENTITY (1,1) PRIMARY KEY,
MARCA NVARCHAR (100)NOT NULL
)
GO

CREATE TABLE PRODUCTOS(
IDPROD INT IDENTITY (1,1) PRIMARY KEY,
IDCATE INT NOT NULL,
IDMAR INT NOT NULL, 
DESCRIPCION NVARCHAR(100) NOT NULL,
PRECIO FLOAT NOT NULL
)
GO

ALTER TABLE PRODUCTOS
ADD CONSTRAINT FK_CATE
FOREIGN KEY (IDCATE)
REFERENCES CATEGORIA (IDCATE)
GO

ALTER TABLE PRODUCTOS
ADD CONSTRAINT FK_MAR
FOREIGN KEY (IDMAR)
REFERENCES MARCA (IDMAR)
GO

INSERT INTO CATEGORIA VALUES
(''),
('PC'),
('Consola'),
('Monitor'),
('TV'),
('Estereo'),
('Celular'),
('Bocina')
GO

INSERT INTO MARCA VALUES
(''),
('TOSHIBA'),
('Samsung'),
('Visio'),
('Lenovo'),
('SONY'),
('Motorola'),
('Iphone'),
('LG'),
('Xbox'),
('PayStation'),
('Nintendo')
GO

CREATE PROCEDURE LISTACATEGORIAS
AS
SELECT*FROM CATEGORIA ORDER BY CATEGORIA ASC
GO

CREATE PROCEDURE LISTAMARCAS
AS
SELECT*FROM MARCA ORDER BY MARCA ASC
GO

-----AGREGAR PRODUCTO
CREATE PROCEDURE AGREGARPRODUC
	@IDCATE INT,
	@IDMAR INT,
	@DESC NVARCHAR (100),
	@PRECIO FLOAT
AS
INSERT INTO PRODUCTOS VALUES
(
	@IDCATE,
	@IDMAR,
	@DESC,
	@PRECIO
)
GO

CREATE PROCEDURE LISTAPRODUC
AS
SELECT	IDPROD, 
		CATEGORIA.CATEGORIA,
		MARCA.MARCA,
		DESCRIPCION,
		PRECIO
FROM PRODUCTOS 
INNER JOIN CATEGORIA 
		ON PRODUCTOS.IDCATE=CATEGORIA.IDCATE
INNER JOIN MARCA 
		ON PRODUCTOS.IDMAR=MARCA.IDMAR
GO

EXEC AGREGARPRODUC 3,11,'Consola PS4 Edicion Especial', 8999

EXEC LISTACATEGORIAS
EXEC LISTAMARCAS
EXEC LISTAPRODUC
SELECT*FROM PRODUCTOS

